### ISSUE TITLE
Is it possible to have a PEP_PROXY_PUBLIC_PATHS like Wilma Pep

### ISSUE THREAD

**Issue by konstantinosGombakis** [FIWARE/kong-plugins-fiware#27]
I want to protect my Orion-LD with the kong-pep-plugin but to expose the orion-ld:1026/version without authentication? 
Is it possible to achieve than with Kong?

**Comment by wistefan** [comment]
Hi, yes. You could just configure a route that does not use the plugin for version and another one for the other endpoints:
```yaml
 services:
      - host: "orion"
        name: "orion-version"
        port: 1026
        protocol: http

        routes:
          - name: orion
            paths: 
              - /version
              - 
      - host: "orion"
        name: "orion"
        port: 1026
        protocol: http
  
        routes:
          - name: orion
            paths: 
              - /ngsi-ld
            plugins:
             - name: pep-plugin
                 ....
```
